spring:
  data:
    mongodb:
      uri: mongodb+srv://sirfayush1008:Ayush%403344@cluster0.ngtgm.mongodb.net/RepoScribe?retryWrites=true&w=majority

cohere:
  apiKey: fRFZdMkAokUJJfFsvkVWHzbouD6oPibUEOpGlwUU
github:
  clientId: Ov23liHofip0pyG42YzZ
  clientSecret: 0b829ea0ee6cf817c45b837616f0712ee6dc9e0f
  redirectUri: https://repo-scribe.vercel.app/auth/callback

  server:
    port: ${PORT:8080}
